name: Fastfetch All Modules to TXT

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  fastfetch-all:
    name: Fastfetch (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        runner:
          # Linux x64
          - ubuntu-slim
          - ubuntu-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-26.04

          # Linux ARM64
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - ubuntu-26.04-arm

          # Windows x64
          - windows-latest
          - windows-2025
          - windows-2025-vs2026
          - windows-2022

          # Windows ARM64
          - windows-11-arm
          - windows-11-vs2026-arm

          # macOS Intel (x64)
          - macos-15-intel
          - macos-26-intel

          # macOS Apple Silicon (ARM64)
          - macos-latest
          - macos-14
          - macos-15
          - macos-26
          - xcode-27

    steps:
      # 1. Linux 패키지 설치
      - name: Install Fastfetch (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository ppa:zhangsongcui3371/fastfetch -y
          sudo apt-get update
          sudo apt-get install -y fastfetch

      # 2. macOS Homebrew 패키지 설치
      - name: Install Fastfetch (macOS)
        if: runner.os == 'macOS'
        run: brew install fastfetch

      # 3. Windows Chocolatey 패키지 설치
      - name: Install Fastfetch (Windows)
        if: runner.os == 'Windows'
        run: choco install fastfetch -y

      # 4. user@hostname.txt 파일명으로 저장
      - name: Run Fastfetch and Save as user@hostname.txt
        run: |
          FILENAME="$(whoami)@$(hostname).txt"
          fastfetch -c all --pipe false > "$FILENAME"

      # 5. 모든 결과를 하나의 아티팩트로 통합 업로드 (한 번에 다운로드 가능)
      - name: Upload Combined Fastfetch Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastfetch-results
          path: "*.txt"
          merge-multiple: true
